# Generated by Django 5.0.9 on 2024-10-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='IndexConstituent',
        ),
    ]
