# Generated by Django 5.0.9 on 2024-10-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_stock_active_delete_indexconstituent'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
