# Generated by Django 5.0.9 on 2024-10-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_indexstock_delete_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexstock',
            name='market_cap',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indexstock',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
