# Generated by Django 5.0.9 on 2024-10-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_indexstock_market_cap_indexstock_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexstock',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
